package main

import (
	"log"
	"os"
	"text/template"
	"time"
)

var tmpl = template.Must(template.New("time.go").Parse(`// Code generated by go generate; DO NOT EDIT.
package main

func Now() string {
	return "{{ .Time }}"
}
`))

type tmplData struct {
	Time string
}

func main() {
	file, err := os.Create("time.go")
	if err != nil {
		log.Fatalln("failed to create file", err)
	}

	tmpl.Execute(file, tmplData{
		Time: time.Now().String(),
	})
}
