name: generate
on:
  schedule:
  - cron: "0 12 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v1
      with:
        go-version: '1.14.3'

    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Generate time.go
      run: go run ./...

    - name: Auto-commit generated time.go
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update time.go file