name: generate
on:
  push:
    branches: [ master ]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v1
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Generate time.go
      run: go run ./...
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update time.go file